# Generated by Django 5.0.7 on 2024-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0002_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=10),
        ),
    ]
