from .agent import *
from .BankFD import *
from .branch import *
from .customer import *
from .DD import *
from .deposit_scheme import *
from .FD import *
from .general_ledger import *
from .Gold import *
from .interest_slab import *
from .loan import *
from .locations import *
from .nominee import *
from .RD import *
from .recovery_officer import *
from .saving import *
from .share import *
from .society import *
from .user import *
from .Vehicle import *