# Generated by Django 5.0.7 on 2024-08-01 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_master', '0003_city_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='d_cities', to='primary_master.district'),
        ),
        migrations.AddField(
            model_name='city',
            name='taluka',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='t_cities', to='primary_master.taluka'),
        ),
    ]
