# Generated by Django 5.0.7 on 2024-08-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_master', '0004_nominee_remove_city_state_remove_state_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pl_bl', models.CharField(choices=[('B', 'Balance Sheet'), ('P', 'P&L')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GL_Master',
            fields=[
                ('gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_gl', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('acc_code', models.CharField(max_length=10, unique=True)),
                ('pl_bl', models.CharField(choices=[('B', 'Balance Sheet'), ('P', 'P&L')], max_length=1)),
                ('int_code', models.IntegerField(default=0, null=True)),
                ('pr_int_code', models.IntegerField(default=0, null=True)),
                ('due_amnt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('int_cal_type', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_cal_type', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pen_cl_type', models.IntegerField(default=0)),
                ('ag_cd', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_type', to='primary_master.acc_type')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_name', to='primary_master.group_master')),
            ],
        ),
    ]
