# Generated by Django 5.0.7 on 2024-08-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_master', '0005_acc_type_group_master_gl_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField()),
                ('particular', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_valuation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('gl_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primary_master.gl_master')),
            ],
        ),
    ]
